name: flutter_helper
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.1
  sqflite: ^2.3.3+1
  fluttertoast: ^8.2.12
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  equatable: ^2.0.3
  path_provider: ^2.0.15
  path: ^1.8.3
  json_annotation: ^4.9.0
  image_picker: ^1.2.0
  pdf: ^3.11.0
  printing: ^5.12.0
  flutter_staggered_animations: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test:

dependency_overrides:
  win32: ^5.5.4


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
