name: expense_tracker
description: "A modern expense tracking application with currency conversion and local storage."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # UI & Responsive Design
  flutter_screenutil: ^5.9.1
  flutter_staggered_animations: ^1.1.1
  
  # Local Storage
  sqflite: ^2.3.3+1
  path_provider: ^2.0.15
  path: ^1.8.3
  
  # Network & API
  dio: ^5.4.3+1
  http: ^1.1.0
  
  # Utilities
  equatable: ^2.0.3
  json_annotation: ^4.9.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # File & Image Handling
  image_picker: ^1.2.0
  permission_handler: ^11.3.1
  
  # PDF Generation
  pdf: ^3.11.0
  printing: ^5.12.0
  
  # URL Launcher
  url_launcher: ^6.3.0
  
  # Toast Messages
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.5
  json_serializable: ^6.8.0
  build_runner: ^2.4.8

dependency_overrides:
  win32: ^5.5.4

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
